version: "3.8"

services:
  app1:
    build:
      context: ../fastapi-file
    container_name: fastapi_app1
    restart: always
    volumes:
      - app1_data:/app/data
    ports:
      - "8001:8000"
    networks:
      - fastapi_network

  app2:
    build:
      context: ../fastapi-file
    container_name: fastapi_app2
    restart: always
    volumes:
      - app2_data:/app/data
    ports:
      - "8002:8000"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge

volumes:
  app1_data:
  app2_data:
